spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/teamflow_ai
spring.datasource.username=${TEAMFLOW_DB_USERNAME}
spring.datasource.password=${TEAMFLOW_DB_PASSWORD}
