spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/teamflow_ai
spring.datasource.username=${TEAMFLOW_DB_USERNAME}
spring.datasource.password=${TEAMFLOW_DB_PASSWORD}

application.security.jwt.secret-key=${TEAMFLOW_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration-ms=${TEAMFLOW_JWT_EXPIRATION:900000}
